#!/usr/bin/env python
#
# https://github.com/exitparadise/esactl.git
# tim talpas github.festive812@passfwd.com
# 

import elasticagent as ea
import argparse, requests, json, os, sys, re
from datetime import datetime

requests.packages.urllib3.disable_warnings() 

parser = argparse.ArgumentParser(description="Elastic Agent Management Utility")
subparsers = parser.add_subparsers(dest="cmd")

parser_ns = subparsers.add_parser("ns", help="namespace actions")
parser_ns.add_argument("action", choices=["list","details"])

parser_template = subparsers.add_parser("template", help="index template actions")
parser_template.add_argument("action", choices=["list","json","init","details","update","createfromgeneric","copy"])
parser_template.add_argument("object", help="the namespace or index template")
parser_template.add_argument("dest", nargs='?', help="when copy, the name to copy to")
parser_template.add_argument("-p", "--pattern", nargs=1, help="when action is 'update', set patterns to this comma delineated list")
parser_template.add_argument("-o", "--prio", nargs=1, type=int, help="when action is 'update', increase/decrease priority to this")
parser_template.add_argument("-c", "--component", nargs=2, help="when action is 'update', add/remove component: <a|add|r|rm|remove> <component>")
parser_template.add_argument("-l", "--lifecycle-policy", nargs=1, help="when action is 'update', add this policy. 'none' means remove policy")
parser_template.add_argument("-d", "--retention-days", nargs=1, type=int, help="when action is 'init' or 'update', number of retention days to apply")

parser_agent = subparsers.add_parser("agent", help="agent policy actions")
parser_agent.add_argument("action", choices=["list","details","copy"])
parser_agent.add_argument("object", nargs="?", help="the namespace or agent policy")
parser_agent.add_argument("dest", nargs="?", help="when action is 'copy', the new agent policy to copy to")
parser_agent.add_argument("namespace", nargs="?", help="when action is 'copy', the namespace to set in new policy")
parser_agent.add_argument("-f", "--full", action="store_true", help="when action is 'json', enable full output")

parser_ds = subparsers.add_parser("ds", help="datastream actions")
parser_ds.add_argument("action", choices=["list","details","applyilm"])
parser_ds.add_argument("object", nargs="?", help="the datastream or namespace we would like to target, used with 'list', 'details' and 'applyilm'")
parser_ds.add_argument("-l", "--show-lifecycle", action="store_true")

parser_ilm = subparsers.add_parser("ilm", help="ILM actions")
parser_ilm.add_argument("action", choices=["list","details","json"])
parser_ilm.add_argument("object", nargs="?", help="the ilm policy we would like to target, used with 'details' and 'json'")

try:
    args = parser.parse_args()
except:
    parser.print_help()
    sys.exit(0)

API_KEY=os.getenv('ELASTIC_API_KEY')
ELASTIC_HOST="elastic-api:9200"
KIBANA_HOST="kibana-api:5601"

SSL_VERIFY=False
SPACES = ('prod','devqa','default')

def main():
    if args.cmd == 'ilm':
        if args.action == 'list':
            ilms = api_request('GET',ELASTIC_HOST,f"_ilm/policy")
            for ilm in ilms:
                print(ilm)
        elif args.action in ('details', 'json'):
            try:
                ilms = api_request('GET',ELASTIC_HOST,f"_ilm/policy/{args.object}")
            except:
                sys.exit(f"could not find ilm policy: {args.object}")

            if args.action == 'json':
                for ilm in ilms:
                    print(json.dumps(ilms[ilm],indent=1))
            else:
                for ilm in ilms:
                    print(f"ilm_policy: {ilm}")
                    print("  phases:")
                    for p in ilms[ilm]['policy']['phases']:
                        ilm_phase_show(p,ilms[ilm]['policy']['phases'][p])    
                    print("  used_by:")
                    for i in ilms[ilm]['in_use_by']['indices']:
                        print(f"  - index: {i}")
                    for d in ilms[ilm]['in_use_by']['data_streams']:
                        print(f"  - datastream: {d}")
                    for c in ilms[ilm]['in_use_by']['composable_templates']:
                        print(f"  - index_template: {c}")
    elif args.cmd == 'ns':
        if args.action in ('list','details'):
            ns = {}
            pol = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies")
            for policy in pol['items']:
                ea.dict_append(ns)[policy['namespace']] = 1
            
            for n in sorted(ns.keys()):
                print(n)
            
    elif args.cmd == 'agent':
        if args.action in ('list','details'):
            if args.object in SPACES:
                pol = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies?kuery=ingest-agent-policies.namespace:{args.object}")
            elif args.object == 'all':
                pol = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies")
            elif args.action == 'details':
                pol = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies?kuery=ingest-agent-policies.name:{args.object}")
            else:
                sys.exit("agent actions require <object>, a valid namespace name")
           
            for policy in pol['items']:
                print(f"{policy['name']}:agents={policy['agents']}")
                if args.action == 'details':
                    print(f"    namespace: {policy['namespace']}")
                    full = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies/{policy['id']}/full")
                    
                    print("    integrations:")
                    for input in full['item']['inputs']:
                        print(f"    - {input['name']} - {input['type']}")
        elif args.action == 'copy':
            if not args.object or not args.namespace or not args.dest:
                sys.exit("copy action requires <object>, an agent policy to copy, <dest>, a name to copy to, and <namespace> the namespace to set in the new policy") 
            else:
                p = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies?kuery=ingest-agent-policies.name:{args.object}")
                policy = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies/{p['items'][0]['id']}")
                #new_name = re.sub("^[^-]+",args.object,args.namespace)

                print(f"copy {policy['item']['name']}/{policy['item']['id']} to {args.dest}")

                (new_policy,packages) = agent_policy_rename(policy['item'], args.dest, args.namespace)
                new_policy_def = api_request('POST',KIBANA_HOST,f"api/fleet/agent_policies",new_policy)
                print(f" - new policy ID: {new_policy_def['item']['id']}")
                
                for pkg in packages:
                   pkg['policy_id'] = new_policy_def['item']['id']
                   # mysql integration password can't be copied, so we remove it and prompt user to re-add through UI
                   W = raise_warn(pkg['package']['name'],'mysql','equals','P')
                   if pkg['package']['name'] == 'mysql':
                       del pkg['secret_references']
                       for input in pkg['inputs']:
                           if input['type'] == 'mysql/metrics':
                               input['vars']['password']['value'] = ""
                               for stream in input['streams']:
                                   try:
                                       del stream['compiled_stream'] 
                                   except:
                                       pass

                   pkgadd = api_request('POST',KIBANA_HOST,f"api/fleet/package_policies",pkg)
                   print(f" - add integration: {pkgadd['item']['name']}/{pkgadd['item']['id']} {W}")
                print("Done!")

        elif args.action == 'json':
            if not args.object:
                sys.exit("json action requires <object>, an agent policy name") 
            else:
                p = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies?kuery=ingest-agent-policies.name:{args.object}")
                if args.full:
                    policy = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies/{p['items'][0]['id']}/full")
                else:
                    try:
                        policy = api_request('GET',KIBANA_HOST,f"api/fleet/agent_policies/{p['items'][0]['id']}")
                    except IndexError:
                        sys.exit(f"agent policy: {args.object} does not exist")
                print(json.dumps(policy,indent=1))

    elif args.cmd == 'ds':
        if args.action in ('list', 'details'):
            if args.object in SPACES:
                resp=api_request('GET',ELASTIC_HOST,f"_data_stream/*-{args.object}?expand_wildcards=all")
            elif args.object and args.object != 'all':
                try:
                    resp=api_request('GET',ELASTIC_HOST,f"_data_stream/{args.object}")
                except:
                    sys.exit(f"could not find datastream: {args.object}")
            elif args.object == 'all':
                resp=api_request('GET',ELASTIC_HOST,f"_data_stream?expand_wildcards=all")
            else:
                sys.exit("datastream actions require <object>, a valid namespace or a datastream name")

            for ds in resp['data_streams']:
               
               #W = raise_warn(args.object,ds['template'],'search','N')
               W = ''

               if args.action == 'details':
                   print(f"{ds['name']}:")
                   print(f"  - index_template: {ds['template']} {W}")
                   try:
                       print(f"  - ilm_policy: {ds['ilm_policy']}")
                   except KeyError: 
                       pass
                   print("  - indices:")

                   if args.show_lifecycle:
                       il = api_request('GET',ELASTIC_HOST,f"{ds['name']}/_ilm/explain")

                       k = list(il['indices'].keys())
                       k.sort()
                       for id in k:

                           a = ea.ilmDetails(il['indices'][id])

                           try:
                               W2 = raise_warn(ds['ilm_policy'],il['indices'][id]['policy'],'equals','M')
                           except KeyError:
                               try:
                                   W2 = raise_warn(ds['ilm_policy'],'None','equals','M')
                               except: 
                                   W2 = ''

                           a.print_details(W2)

                   else:
                       for index in ds['indices']:
                           try:
                               W2 = raise_warn(ds['ilm_policy'],index['ilm_policy'],'equals','M')
                               print(f"    {index['index_name']} ilm:{index['ilm_policy']} {W2}")
                           except KeyError:
                               print(f"    {index['index_name']}")

               else:
                   print(f"{ds['name']} template:{ds['template']} {W}")
                  
        elif args.action == 'applyilm':
            if args.object:
                resp=api_request('GET',ELASTIC_HOST,f"_data_stream/{args.object}")
            else:
                sys.exit("applyilm action requires <object>, a datastream name")

            for ds in resp['data_streams']:
               print(f"applying {ds['ilm_policy']} to all indexes in {ds['name']}")
               for index in ds['indices']:
                   if ds['ilm_policy'] == index['ilm_policy']:
                       print(f"{index['index_name']} already has policy {ds['ilm_policy']}, skipping")
                   else:
                       print(f"update {index['index_name']} from {index['ilm_policy']} to {ds['ilm_policy']}")
                       payload = { "index.lifecycle.name": ds['ilm_policy'], "index.lifecycle.prefer_ilm": True }
                       resp = api_request('PUT',ELASTIC_HOST,f"{index['index_name']}/_settings",payload)
                       print(resp)
          
    elif args.cmd == 'template':
        if args.action == 'init' and args.object in SPACES:
            template_recreate_from_ds(args.object)
        elif args.action == 'copy':
            try:
                t = ea.indexTemplate(api_request('GET',ELASTIC_HOST,f"_index_template/{args.object}"))
            except:
                sys.exit(f"index template '{args.object}' not found")

            t.update_name(args.dest)
            t.unmanage("self")

            res = api_request('POST',ELASTIC_HOST,f"_index_template/{t.name}",t.template)
        elif args.action == 'createfromgeneric':
            if not args.object:
               sys.exit("createfromgeneric requires the name of an existing generic template appended with '-<namespace>'")

            g = re.sub("\-[^-]+$","",args.object)
            n = re.findall("[^-]+$",args.object)
            namespace = n[0]

            try:
                t = ea.indexTemplate(api_request('GET',ELASTIC_HOST,f"_index_template/{g}"))
            except:
                sys.exit(f"generic index template '{g}' not found")

            t.update_name(args.object)
            ps = t.get_patterns()
            print(ps[0])
            if ps[0] == "metrics-*-*":
                new_pattern =  (f"metrics-*-{namespace}")
                prio = 149
            elif ps[0] == "logs-*-*":
                new_pattern = (f"logs-*-{namespace}")
                prio = 149
            else:
                new_pattern = ps[0].replace("-*",f"-{namespace}*",1)
                prio = 250
            ps[0] = new_pattern
            t.update_patterns(ps)
            t.unmanage("prth")
            t.update_prio(prio)

            res = api_request('POST',ELASTIC_HOST,f"_index_template/{t.name}",t.template)
            print(json.dumps(res,indent=1))
        elif args.action == 'json':
            if args.object:
                try:
                    t = ea.indexTemplate(api_request('GET',ELASTIC_HOST,f"_index_template/{args.object}"))
                    t.print_json()
                except:
                    sys.exit(f"template not found: {args.object}")
            else:
                sys.exit(f"json action requires <object>, an index template name")
        elif args.action in ('list', 'details'):
            if args.object in SPACES:
                resp=api_request('GET',ELASTIC_HOST,f"_index_template/*-{args.object}")
            elif args.action == 'details' and args.object:
                try:
                    resp=api_request('GET',ELASTIC_HOST,f"_index_template/{args.object}")
                except:
                    sys.exit("template actions require <object>, a valid namespace or index template name")
            else:
                sys.exit("template actions require <object>, a valid namespace or index template name")

            for t in map(ea.indexTemplate, resp['index_templates']):
               W = raise_warn(args.object, t.name, 'search', 'N')
               print(f"{t.name} {W}")
               if args.action == 'details':
                   t.print_details()

        elif args.action == 'update':
            t = ea.indexTemplate(api_request('GET',ELASTIC_HOST,f"_index_template/{args.object}"))
            changes = 0
            if args.component:
                changes += t.update_component(args.component)
            if args.lifecycle_policy in ('none','None',0):
                changes += t.update_ilm_policy(None)
            elif args.lifecycle_policy:
                changes += t.update_ilm_policy(args.lifecycle_policy)
            if args.retention_days == 0 or args.retention_days:
                changes += t.update_retention(args.retention_days)
            if args.prio:
                changes += t.update_prio(args.prio)
            if args.pattern:
                patterns = []
                for p in args.pattern[0].split(","):
                    patterns.append(p);

                changes += t.update_patterns(patterns)

            if changes:
                res = api_request('POST',ELASTIC_HOST,f"_index_template/{args.object}",t.template)
                print(f"updating template {t.name} with {changes} changes")
                print(json.dumps(res,indent=1))
            else:
                print(f"no changes to make for template: {t.name}")

    else:
        parser.print_help()
        sys.exit(1)
    print_warns(ea.WARN)

def agent_policy_rename(POLICY,NAMESPACE,NAME):
    for d in ('id','version','revision','updated_at','updated_by','agents',
              'unprivileged_agents','status','is_managed','is_protected','schema_version','inactivity_timeout'):
        del POLICY[d]
    
    POLICY['namespace'] = NAMESPACE
    POLICY['name'] = NAME

    new_packages = []
    for p in POLICY['package_policies']:
        new_name = re.sub("^[^-]+",NAMESPACE,p['name'])
        new_name = re.sub(" \(.*\)","",new_name)
        p['name'] = new_name
        for d in ('id','version','updated_at','updated_by','revision','created_at','created_by','policy_id','policy_ids'):
            del p[d]

        new_inputs = []
        for i in p['inputs']:
            new_streams = []
            for s in i['streams']:
                del s['id']
                new_streams.append(s)

            del i['streams']
            i['streams'] = new_streams

            new_inputs.append(i)

        del p['inputs']
        p['inputs'] = new_inputs

        new_packages.append(p)

    del POLICY['package_policies']
    #POLICY['package_policies'] = new_packages
    return POLICY,new_packages

def ilm_phase_show(P,PHASE):
    print(f"  - {P}:")
    print(f"    min_age: {PHASE['min_age']}")
    print("    actions:")
    for a in PHASE['actions']:
        print(f"      - {a}")

def raise_warn(a,b,action,type):
    _warns = { 
               'N': "[!N] = not using a namespaced template",
               'M': "[!M] = ilm mismatch: index has different policy from datastream",
               'P': "[!P] = unable to copy passwords, edit integration through the UI to re-add"
             }

    if action == 'equals' and a == b:
        return ""
    elif action == 'search' and re.search(a, b):
        return ""
    else:
        ea.WARN[type] = _warns[type]
        return f"[!{type}]"

def print_warns(WARNS):
    for w in WARNS:
        print("* " + WARNS[w])
        
def agent_policy_rename(POLICY,NAME,NAMESPACE):
    for d in ('id','version','revision','updated_at','updated_by','agents',
              'unprivileged_agents','status','is_managed','is_protected','schema_version','inactivity_timeout'):
        del POLICY[d]
    
    POLICY['namespace'] = NAMESPACE
    POLICY['name'] = NAME

    new_packages = []
    for p in POLICY['package_policies']:
        new_name = re.sub("^[^-]+",NAMESPACE,p['name'])
        new_name = re.sub(" \(.*\)","",new_name)
        p['name'] = new_name
        for d in ('id','version','updated_at','updated_by','revision','created_at','created_by','policy_id','policy_ids'):
            del p[d]

        new_inputs = []
        for i in p['inputs']:
            new_streams = []
            for s in i['streams']:
                del s['id']
                new_streams.append(s)

            del i['streams']
            i['streams'] = new_streams

            new_inputs.append(i)

        del p['inputs']
        p['inputs'] = new_inputs

        new_packages.append(p)

    del POLICY['package_policies']
    return POLICY,new_packages

def api_request(METHOD,HOST,LOC,PAYLOAD=None):
    url = f'https://{HOST}/{LOC}'
    headers = {
        'kbn-xsrf': 'reporting',
        'Content-Type': 'application/json',
        'Authorization': f'ApiKey {API_KEY}',
        'Elastic-Api-Version': '2023-10-31'
    }
    if METHOD == 'GET':
        response = requests.get(url, headers=headers, verify=SSL_VERIFY)
    elif METHOD == 'POST':
        response = requests.post(url, headers=headers, json=PAYLOAD, verify=SSL_VERIFY) 
    elif METHOD == 'PUT':
        response = requests.put(url, headers=headers, json=PAYLOAD, verify=SSL_VERIFY) 
    else:
       sys.exit(f"method {METHOD} not recognized")

    if response.status_code == 200:
        content = response.json()
        return content
    else:
        response.raise_for_status()

def template_recreate_from_ds(NAMESPACE):
    # get list of all data streams in namespace, and the current templates
    # then create new templates specific for that namespace
    action=(f"_data_stream/*-{NAMESPACE}")
    dstreams = api_request('GET',ELASTIC_HOST,action)
    for ds in dstreams['data_streams']:
        if "-"+NAMESPACE in ds['template']:
            print(f"Namespaced template {ds['template']} already exists...")
            continue

        resp = api_request('GET',ELASTIC_HOST,f"_index_template/{ds['template']}")

        template = resp['index_templates'][0]['index_template']
        template_name = resp['index_templates'][0]['name']
        index_pattern=template['index_patterns'][0]
        
        new_name = (f"{template_name}-{NAMESPACE}") 

        ## replace data in old template definition with new values 
        # we have to deal with generic/catchall templates differently
        # higher prio = pattern will be matched first before a matching pattern in a lower priority template
        if index_pattern == "metrics-*-*":
            new_pattern =  (f"metrics-*-{NAMESPACE}")
            new_prio = template['priority'] + 49
        elif index_pattern == "logs-*-*":
            new_pattern =  (f"logs-*-{NAMESPACE}")
            new_prio = template['priority'] + 49
        else:
            new_pattern =  index_pattern.replace("-*",f"-{NAMESPACE}*",1)
            new_prio = template['priority'] + 50
   
        # add lifecycle policy:  metrics-NAMESPACE or logs-NAMESPACE
        if "metrics" in index_pattern:
            try: 
                template['template']['settings'] = {'index': {'lifecycle': { 'name': 'metrics-'+NAMESPACE } } }
            except KeyError:
                template['template'] = {'settings': {'index': {'lifecycle': { 'name': 'metrics-'+NAMESPACE } } } }
        elif "logs" in index_pattern:
            try:
                template['template']['settings'] = {'index': {'lifecycle': { 'name': 'logs-'+NAMESPACE } } }
            except KeyError:
                template['template'] = {'settings': {'index': {'lifecycle': { 'name': 'logs-'+NAMESPACE } } } }
        else:
            print (f"{index_pattern} doesn't look like a template we can manage")

        # specify data retention in template if desired
        if args.retention_days:
            template['template']['lifecycle'] = { "enabled": "true", "data_retention": str(args.retention_days)+"d" }

        template['index_patterns'][0] = new_pattern
        template['priority'] = new_prio
        template['_meta']['managed_by'] = "prth"
        template['_meta']['managed'] = False
        resp = api_request('PUT',ELASTIC_HOST,f"_index_template/{new_name}",template)
        print(resp)

if __name__ == '__main__':
    main()
